version: "3.3"

services:
    nginx:
        container_name: nginx
        image: ${NGINX_IMAGE}
        restart: always
        ports:
            - ${WEB_PORT}:6700
        environment:
            WEB_CLIENT_HOST: web-client
        volumes:
            - ../nginx:/etc/nginx/templates
        depends_on:
            - web-client
    web-client:
        container_name: web-client
        build:
            context: ../../services/web-client
            args:
                NODE_IMAGE: ${NODE_IMAGE}
                PROJECT_NAME: ${PROJECT_NAME}
        restart: always
        entrypoint: yarn start
