version: "3.3"

services:
    nginx:
        container_name: nginx
        image: ${NGINX_IMAGE}
        restart: always
        ports:
            - ${WEB_PORT}:6700
        environment:
            WEB_CLIENT_HOST: web-client
            API_HOST: api
        volumes:
            - ../nginx:/etc/nginx/templates
        depends_on:
            - web-client
    web-client:
        container_name: web-client
        build:
            context: ../../services/web-client
            args:
                NODE_IMAGE: ${NODE_IMAGE}
                PROJECT_NAME: ${PROJECT_NAME}
        restart: always
        environment:
            API_HOST: nginx
        entrypoint: yarn start
        depends_on:
            - api
    api:
        container_name: api
        build:
            context: ../../services/api
            args:
                NODE_IMAGE: ${NODE_IMAGE}
        restart: always
        environment:
            MONGO_HOST: mongo
            MONGO_DB_NAME: ${MONGO_DB_NAME}
            LOCAL_CLIENT_SECRET: ${LOCAL_CLIENT_SECRET}
            GMAIL_USERNAME: ${GMAIL_USERNAME}
            GMAIL_PASSWORD: ${GMAIL_PASSWORD}
            GMAIL_NAME: ${GMAIL_NAME}
        entrypoint: yarn start
        depends_on:
            - mongo
    mongo:
        container_name: mongo
        image: ${MONGO_IMAGE}
        restart: always
        ports:
            - ${MONGO_PORT}:27017
        volumes:
            - ../../volumes/mongo:/data/db
