version: "3.3"

services:
    nginx:
        container_name: nginx
        image: ${NGINX_IMAGE}
        restart: always
        network_mode: host
        ports:
            - ${WEB_PORT}:6700
        environment:
            WEB_CLIENT_HOST: localhost
            API_HOST: localhost
        volumes:
            - ../nginx:/etc/nginx/templates
    mongo:
        container_name: mongo
        image: ${MONGO_IMAGE}
        restart: always
        ports:
            - ${DB_PORT}:27017
        volumes:
            - ../../volumes/mongo:/data/db
